name: New Era app

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  # Continuous Integration (CI)
  build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:17
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: 1
          POSTGRES_DB: shop
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready -U test_user"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    steps:
      # Checkout code
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      # Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Set up environment variables for tests
      - name: Set up environment variables
        run: |
          echo "DATABASE_URL=postgresql+asyncpg://postgres:1@localhost:5432/shop" >> $GITHUB_ENV

      # Run migrations (Alembic with async)
      - name: Run async database migrations
        run: |
          alembic upgrade head

      # Run tests
      - name: Run tests
        run: |
          pytest --cov=app tests/